# https://medium.com/@vhsilva.ap/configurando-laravel-6-nginx-e-postgresql-com-docker-9ad29c53d5

# https://hub.docker.com/_/postgres

FROM postgres:15-alpine3.17
RUN apk add --no-cache openssl bash net-tools

# WORKDIR /var/www

# RUN rm -rf /var/www/html
# RUN ln -s public html

# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# COPY . /var/www

# RUN chmod -R 777 /var/www/storage

EXPOSE 5423

# ENTRYPOINT [ "php-fpm" ]
