# https://medium.com/@vhsilva.ap/configurando-laravel-6-nginx-e-postgresql-com-docker-9ad29c53d5

# https://stackoverflow.com/questions/39493490/provide-static-ip-to-docker-containers-via-docker-compose

# reset de senha wsl
# https://valchan.com.br/wsl-reset-pass/
# EEeric1000

version: '3'

services: 
  web:
    container_name: my_web
    restart: always
    build: .
    volumes: 
      - ./:/var/www/
    depends_on: 
#      - db
      - postgres-compose

    networks:
      - postgres-network

    ports:
      - "9000:9000"

  postgres-compose:
    container_name: my_db
    restart: always
#    image: postgres
    build: ./.docker/postgres
    environment:
      POSTGRES_PASSWORD: "bi#pjePENTAHO"
      PGADMIN_DEFAULT_EMAIL: "postgres"
    ports:
#psql -U postgres -p 5432 -h localhost"nome do banco"<"nome do arquivo de backup".sql
      - "15432:5432"
    volumes:
#      - /home/renatogroffe/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
#      - /volumes/php+nginx+postgres/data:/var/lib/postgresql/data 
#      - /volumes/php+nginx+postgres/data2:/var/lib/postgresql/data 
      - /volumes/php+nginx+postgres/data3333:/var/lib/postgresql/data 
      - ./:/temp

    networks:
      - postgres-network

  nginx:
    container_name: my_app
    build: ./.docker/nginx
    restart: always
    ports:
      - "8000:80"
    volumes: 
      - ./:/var/www
    depends_on: 
      - web

    networks:
      - postgres-network


networks: 
  postgres-network:
    driver: bridge

