# https://medium.com/@vhsilva.ap/configurando-laravel-6-nginx-e-postgresql-com-docker-9ad29c53d5

# https://stackoverflow.com/questions/39493490/provide-static-ip-to-docker-containers-via-docker-compose

# reset de senha wsl
# https://valchan.com.br/wsl-reset-pass/
# EEeric1000

version: '3'

services: 
  web:
    container_name: my_web
    restart: always
    build: .
    volumes: 
      - ./:/var/www/
    depends_on: 
#      - db
      - postgres-compose
    networks:
      - postgres-network
    ports:
      - "9000:9000"


  postgres-compose:
    container_name: my_db
    restart: always
    image: postgres
#    build: ./.docker/postgres
    environment:
      POSTGRES_PASSWORD: "bi#pjePENTAHO"
      PGADMIN_DEFAULT_EMAIL: "postgres"
    ports:
#psql -U postgres -p 5432 -h localhost"nome do banco"<"nome do arquivo de backup".sql
      - "5432:5432"
    volumes:
#      - /home/renatogroffe/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
#      - /volumes/postgres/PJe_data:/var/lib/postgresql/data
      - /volumes/php/creche/data:/var/lib/postgres/data
      - ./:/temp

    networks:
      - postgres-network

  postgres-pje:
    container_name: my_db_pje
    restart: always
    image: postgres
#    build: ./.docker/postgres
    environment:
#      POSTGRES_PASSWORD: "P123456"
      POSTGRES_PASSWORD: "bi#pjePENTAHO"
      PGADMIN_DEFAULT_EMAIL: "postgres"
    ports:
#psql -U postgres -p 5432 -h localhost"nome do banco"<"nome do arquivo de backup".sql
      - "15433:5432"
    volumes:
#      - /home/renatogroffe/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
#      - /volumes/php/creche/data:/var/lib/postgres/data
      - /volumes/postgres/PJe_data22:/var/lib/postgresql/data
      - /volumes/postgres/splitado:/tmp
      - ./:/temp

    networks:
      - postgres-network



  postgres-pje-2g:
    container_name: my_db_pje_2g
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: "bi#pjePENTAHO"
      PGADMIN_DEFAULT_EMAIL: "postgres"
    ports:
      - "15434:5432"
    volumes:
      - /volumes/postgres/PJe_data_2g:/var/lib/postgresql/data
      - /volumes/postgres/splitado:/tmp
      - ./:/temp

    networks:
      - postgres-network



  nginx:
    container_name: my_app
    build: ./.docker/nginx
    restart: always
    ports:
      - "8000:80"
    volumes: 
      - ./:/var/www
    depends_on: 
      - web

    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge
