# https://medium.com/@vhsilva.ap/configurando-laravel-6-nginx-e-postgresql-com-docker-9ad29c53d5

# https://stackoverflow.com/questions/39493490/provide-static-ip-to-docker-containers-via-docker-compose

# reset de senha wsl
# https://valchan.com.br/wsl-reset-pass/
# EEeric1000

version: '3'

services: 

  postgres-compose3:
    container_name: my_db3
    restart: always
    image: postgres3
    build: ./.docker/postgres
    environment:
      POSTGRES_PASSWORD: "bi#pjePENTAHO"
      PGADMIN_DEFAULT_EMAIL: "postgres"
    ports:
#psql -U postgres -p 5432 -h localhost"nome do banco"<"nome do arquivo de backup".sql
      - "54323:5432"
    volumes:
#      - /home/renatogroffe/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
#      - /volumes/postgres/PJe_data:/var/lib/postgresql/data
      - /volumes/php/creche/data3:/var/lib/postgres/data
      - ./:/temp

    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge
